### ISSUE TITLE
Bug: "ok" sound has long cooldown.

### ISSUE THREAD

**Issue by Socapexxx** [CompositeLight/currentRMS-helper#14]
After using the extension for a while, I'm finding that the sound takes a while to cooldown. If I scan things slowly, the sound is played consistently, but if I speed up it will sometimes not play the sound, but the scan will go through. This is confirmed by turning the CRMS sounds back on

**Comment by hwrichardson999** [comment]
Hello! Huge fan of this extension, making huge differences in the warehouse. We've noticed this - is there a way the sound can stack so the new sound always has priority? So it cuts off the old sound for the new one?

**Comment by ClearsoundPro** [comment]
I think the sounds have been fixed with the latest version, we just tested this, all works better now


		
Dan Ridd
Director, Clearsound Productions Ltd
01608 665061 <tel:01608 665061> | 07976 627833 <tel:07976 627833> | ***@***.*** ***@***.***>
www.clearsound.co.uk <http://www.clearsound.co.uk/>
10 Tilemans Park, Shipston on Stour, CV36 4GX
 <http://facebook.com/clearsoundproductions>	 <http://twitter.com/clearsoundpro>
IMPORTANT: The contents of this email and any attachments are confidential. They are intended for the named recipient(s) only. If you have received this email by mistake, please notify the sender immediately and do not disclose the contents to anyone or make copies thereof.

**Comment by Socapexxx** [comment]
Hmm I was using 1.20 this morning. I'll have to download it again tomorrow and double check I got it right.

**Comment by CompositeLight** [comment]
Development 1.20.1 has quicker sounds, but have just realised a better way to play them also. See 1.20.2 of the development branch for overlapping sounds. I'm not currently at the warehouse, so can't try this with a scanner, but hammering enter on an empty allocate box seems to work. Let me know if this is working for you.

**Comment by ClearsoundPro** [comment]
Works Great

Rapid fire!!




		
Dan Ridd
Director, Clearsound Productions Ltd
01608 665061 <tel:01608 665061> | 07976 627833 <tel:07976 627833> | ***@***.*** ***@***.***>
www.clearsound.co.uk <http://www.clearsound.co.uk/>
10 Tilemans Park, Shipston on Stour, CV36 4GX
 <http://facebook.com/clearsoundproductions>	 <http://twitter.com/clearsoundpro>
IMPORTANT: The contents of this email and any attachments are confidential. They are intended for the named recipient(s) only. If you have received this email by mistake, please notify the sender immediately and do not disclose the contents to anyone or make copies thereof.

**Comment by CompositeLight** [comment]
Job done.

**Comment by hwrichardson999** [comment]
Hello,

We've been using the app all day today, scanning back in, on global check in or check in on the opportunity is great. It's rapid.

However, on the opportunity scanning out is still very slow - the alert sound seems to be played, not the scan out, and it doesn't overlap, so sometimes scans are missed. Is that a bug or is it mean to play the same sound?

**Comment by CompositeLight** [comment]
That doesn’t sound ideal…

One thing we’ve seen on and off, ever since we’ve been using Current (including prior to using the extension), is where the servers are slow responding. We’re not sure if this is our internet being slow, AWS having an off day, or something else or both. But the symptom is that you scan an item, there’s a pause, then an error noise, then a success sound. I’m not sure exactly, but it’s as though there’s an inbuilt time limit for how long the page will wait for a server response before it assumes there’s a problem - and makes the error noise. This seems to happen even if CurrentRMS is muted…

Does that describe what you’re experiencing?

It would help also if you can right click on the page, select Inspect and got to Console. If the extension is having issues you should see error messages here that might provide a clue as to what’s going wrong.

**Comment by TechJed** [comment]
We’ve found that the more items a job has, the slower the page will run, so if a job is a big job and has 5000+ items it can sometimes crash the devices. I’d be interested to know if this happens on smaller jobs?

**Comment by ClearsoundPro** [comment]
We definitely have slow days with current loading, scanning and adding products, apparently it's our end when I challenge current, blaming our internet, even though we have a very good infrastructure and a supper fast lease line, it especially happens on bigger jobs.

**Comment by TechJed** [comment]
> We definitely have slow days with current loading, scanning and adding products, apparently it's our end when I challenge current, blaming our internet, even though we have a very good infrastructure and a supper fast lease line, it especially happens on bigger jobs.

Can confirm we have the same issues and have had the same response. Dedicated leased line, issues on any device, not just WiFi etc
