### ISSUE TITLE
Feature Request: Show weight on pick line

### ISSUE THREAD

**Issue by b0ngw4ter** [CompositeLight/currentRMS-helper#42]
there are some bulk items where we need to pick hundreds and it would be helpful to be able to single these out to be picked by weight instead of quantity. 

example: 
there is not a counting weighing scale to hand.
i need 79 deck levellers, and know that they weigh 14.6g each. 
if the pick list told me i needed 1139g, i could put a bunch on cheap kitchen scales to count the correct ammount without doing a calculation.

thanks :)

**Comment by CompositeLight** [comment]
Thanks for your suggestion. I do like this idea, and it's something we've talked about here in the past, but I think there's quite a limited scope of items it would work with. For example, ideally you would weigh stage bolts instead of counting them, but if the quantity is enough that you need to weigh them instead of counting it's probably enough that an M12 could be hiding in a pile of M10s... So it needs to be an item that you can visually check quickly, but doesn't live in a box or bag, but is light enough you could weigh... All I can think of is stage packers as you describe, and so creating a whole system to calculate the weight just for that seems like a lot of work. My suggestion would be to stick a sheet up on the wall next to your scales that says how much 5, 10, 15, 20, 25... of them weigh and just use that. For now, closing this as unplanned.
