### ISSUE TITLE
Feature Request: Book Out containers within containers

### ISSUE THREAD

**Issue by kennioje** [CompositeLight/currentRMS-helper#60]
When you Book Out a container (outer) which containers other containers (inner) in vanilla CurrentRMS, the contents of the inner containers isn't booked out. It would be useful if this could be remedied. I guess this process would have to be itterative so that however deep your container tree goes they will be booked out.

This difficulty is that it is possible to have circular references - a container containing its parent or grandparent or great-grandparent, etc. So I guess you'd have to abandon processing that branch if that container already exists in that book out process tree, and move onto the next branch.

**Comment by CompositeLight** [comment]
This is another one where I had to actually go and check what you're saying is correct - because I couldn't believe this wasn't already a thing...! Definitely needs fixing.

I've just re-written the container weights code, which now creates a full map of containerisation. I think that should enable me to sort this out in the future.

The circular containerisation is nuts; I don't understand how they ever allowed this. As part of the new weights calc I've had to add a check to see if there are any loops, and if so those get ignored (which is how I would deal with it at booking out also). At least now you get a warning that you've made the mistake, so you can sort it out.

**Comment by CompositeLight** [comment]
Added to the development branch for testing: 

> "NEW: 1.31.10 - Auto Book Out Nested Containers - This setting is OFF by default, so you'll want to enable it in the settings popup. When enabled, if you you scan a container to book it out and nested containers (and therefore their contents) will also be booked out automatically. Only containers with the status "Prepared" will be auto-booked out (this is to avoid accidentally changing a forgotten "Reserved" item into "Booked Out", but be aware that this can still happen(!) because CurrentRMS will just book out the first level contents of a container regardless of its status, and I can't currently block this insane behaviour)."

Have done some office based testing and it seems to behave. Have a play and let me know how you get on.

**Comment by CompositeLight** [comment]
You're very welcome - thanks for the suggestion!
