### ISSUE TITLE
Bug: Sound not working on opportunities pages

### ISSUE THREAD

**Issue by kennioje** [CompositeLight/currentRMS-helper#61]
Extension sound isn't working on the Opportunities pages (but is on other pages).
Browser: Edge 127.0.2651.86 (Official build) (64-bit) (on Windows 11)
Extension version: 1.31.11(release & development)

Edge reports:
```
Uncaught (in promise) NotAllowedError: play() failed because the user didn't interact with the document first.

Context
https://{removed}.current-rms.com/opportunities/4147?sort=status&view=d

Stack Trace
scripts/content.js:2557 (anonymous function)
```

This was working previously. It changed when I installed 1.31.11 replacing 1.31.8, but that may be correlation rather than causation.
Note - there are no API details entered, so an error is displayed as soon as the page is loaded.

**Comment by kennioje** [comment]
It looks like it might have something to do with [media-engagement](edge://media-engagement/)

**Comment by kennioje** [comment]
Changing edge://settings/content/mediaAutoplay to allow lets the sound for the first error ("Quarantines list was not found. Feature disabled") to play, but no other sounds after that, such as when entering "container".

**Comment by kennioje** [comment]
Rolling back to 1.31.8 has fixed the issue, except for that first "Quarantines" error, so I think that one is to do the mediaAutoplay, whilst everything else is something else that changed between 1.31.8 & 1.31.11

**Comment by kennioje** [comment]
Setting "CurrentRMS Helper Sounds On" to False, page refresh, then setting back to True, page refresh, seems to have solved it. Maybe just something got out of sync on my end. Weird.

I'll leave this here, so you can check there's nothing else that needs looking at with this, and so other people can find it if they have the same problem. I'll close it in a few days if nothing else comes to light.

**Comment by CompositeLight** [comment]
Hi - thanks for this. It's a known/standard issue/limitation that most browsers won't allow sounds to play from a webpage unless the user has first had some kind of interaction (ie. clicked on something). So normally toast messages on a page reload don't/can't make a sound because the browser won't allow it - although your edge setting seems to have overcome this.

However, I think there is still an issue with how the Helper Sounds setting gets saved and loaded. I sorted one bug with it recently, but definitely something still not quite right. If you come across any other clues let me know.
