### ISSUE TITLE
Hide Buttons

### ISSUE THREAD

**Issue by hwrichardson999** [CompositeLight/currentRMS-helper#73]
Hi,

When using the Hide Prepared, Hide Sub-Rents etc, the blue drop down buttons for edit don't appear, the drop down doesn't work. Is there a way these can work? 

Now Current have integrated the Hide Completed, Hide Prepared etc in the functions menu, is it possible to have the Current RMS button for this appear on Allocate, Prepare, Book Out, Check In etc and hide the buttons the app adds? Reason being, on our smaller Zebra scanners they clutter up the screen.

**Comment by CompositeLight** [comment]
Hello! Sorry for the slow response - it's been a busy time. Thank you for reporting the drop down memory bug. I ran into it a few times, but wasn't sure if I was confusing myself. It was confusing because only some filters caused the error. Have nailed that down now and added a fix to 1.31.17 (currently on the Development branch but will be added to the main after testing).

In terms of the other buttons, I'm reluctant to remove the buttons because the Current RMS filters can't be used in combination; you can only choose one at a time. We find it quite useful to use many at once (for example hiding sub hires and hiding prepared at the same time). Also, the in built ones are hidden in the function tab, with no indication that they're turned on without going back to that tab.

That said, I totally hear you that there are now too many buttons for small screens. It was the main reason I resisted adding more buttons for so long, but people kept asking for them... I think the solution is to add some CSS to collapse the button set to a dropdown when the page width is below a threshold. I'll look into it when I can. Could you let me know what screen resolution your zebra scanners are?

**Comment by kennioje** [comment]
> In terms of the other buttons, I'm reluctant to remove the buttons because the Current RMS filters can't be used in combination; you can only choose one at a time. We find it quite useful to use many at once (for example hiding sub hires and hiding prepared at the same time). Also, the in built ones are hidden in the function tab, with no indication that they're turned on without going back to that tab.

I entirely agree, the visibility of these buttons, and being able to combine them, is very much a positive.

> That said, I totally hear you that there are now too many buttons for small screens.
I had wondered if the filters could be aware of which 'tab' (Allocate / Prepare / Book Out / Check-in) is selected and therefore become some form of 'Hide before relevant' and 'Hide after relevant'. Before hiding things that aren't in the state before the tab, and after hiding the things already dealt with by that tab; for example, on the book out tab the 'before' filter would hide anything that was 'Reserved' or 'Allocated', whilst the 'after' filter would hide anything 'Booked out', 'Checked-in' or 'Completed'. Using both together would leave only the things which can be directly dealt with in that tab.

Bonus points are probably available if the filters on the allocate tab change depending on whether 'Mark as Prepared' is on.

**Comment by CompositeLight** [comment]
I made a right mess of that. Should be working as advertised in 1.31.18.

**Comment by kennioje** [comment]
> I made a right mess of that. Should be working as advertised in 1.31.18.

All working right for me now. That is what development builds & testers are for!

I've edited my comment above, because I'd formatted it badly. I've also expanded my thoughts a little.
