### ISSUE TITLE
Feature Request: Add another custom barcode that changes the active element to the container text box

### ISSUE THREAD

**Issue by epictechmedia** [CompositeLight/currentRMS-helper#8]
Similar to the 'freescan' barcode, it would be useful to be able to select the 'container' input by just scanning a barcode without having to return to the desk.

**Comment by CompositeLight** [comment]
Have been wondering about this also... So I'm currently thinking the workflow would be:

1) Scan the "set container" barcode.
2) Scan the asset you want to be the container.
** Container field is populated with the asset number just scanned, and the asset is allocated/prepared if it isn't already? **
3) Scanning the "set container" barcode twice clears the container field.

Any comments / suggestions / additions?

**Comment by Socapexxx** [comment]
I've seen other systems that will "open a case" when a a case is scanned. Fully understand how this is unlikely to be possible, so a generic barcode for "set container" is great.

But since the case asset would already be on the page, would it be possible to scan the containers asset to clear it and revert to normal scanning?

**Comment by ClearsoundPro** [comment]
watching this 1 with an eagle eye, I like the idea of clearing it by scanning the container asset

**Comment by CompositeLight** [comment]
All of this is doable, however there's a major change I want to try to make first. At the moment the *freescan* feature works like this:

1. You scan the *freescan* barcode
2. The system send it to the CurrentRMS servers and it's rejected because it doesn't match an asset
3. A Toast Message is generated because of the failed scan, triggering a failed BUZZ.
4. CRMS Helper spots the keyword "freescan" in the Toast Message
5. CRMS Helper triggers code to turn on freescan

So, it's a bit inefficient, and the failed buzz isn't ideal. It would be better if the keyword could be picked up server side... But since we might be waiting a while on that, I'm working on a way to intercept scan submissions after step 1, so it jumps straight to step 5 without sending to the servers.

This would open up a lot of potential around "special codes" and combined with an API call that identifies cases based on a "container_type" custom field it could be very interesting. Not just along the lines of Socapexxx's comment where it could intelligently open and close cases, but also with things like alerting users if a case is overloaded.

So, for now, resisting the urge to do a quick "container barcode" hack, and will push this forward when I can.

**Comment by ClearsoundPro** [comment]
Just a very early morning thought...

As the fail buzz is nearly always followed by a voice prompt, maybe make the fail buzz less offensive

That way you could keep both "alert sound" then "free scan on"

**Comment by ClearsoundPro** [comment]
Looks like you already nailed it in v1.8 😀

**Comment by CompositeLight** [comment]
I've found a way to intercept scans and handle them differently. It _seems_ to work ok - there's a bit of fudging going on because the built in jQuery function that runs autocomplete was getting very confused... Needs testing a bit to make sure nothing else is now broken as a result.

**Comment by CompositeLight** [comment]
Ok... Have made some progress - check out the development branch for a first attempt. I've managed to get most of the behaviour in; see the 1.20 readme for info. Has not been tested in the warehouse at all as yet. If anyone gets a chance let me know if you find any issues or have any suggestions.

Also on containers, have introduced a different scan sound when you're scanning into a container. The problem I'm trying to tackle is where you have a short break in scanning, and when you pick it back up you forget you've got a container value set. And/or you think you're scanning into a container, but actually you're not because the page reloaded when you reverted an item and it cleared the box. Am not sure if the "container scan" sound is sufficiently different from an ordinary scan. Needs trialling in the warehouse, but let me know what anyone thinks about this.

https://github.com/CompositeLight/currentRMS-helper/tree/development

**Comment by CompositeLight** [comment]
Have updated the development branch with a more different sound...

**Comment by Socapexxx** [comment]
Tested it today and it works flawlessly!

**Comment by CompositeLight** [comment]
Open to further feedback, but for now I'm calling this case closed.
